FROM node:22-slim
WORKDIR /app

RUN npm i -g pnpm

COPY package.json pnpm-workspace.yaml* tsconfig.base.json tsconfig.json ./
COPY libs ./libs
COPY apps ./apps

RUN pnpm install --ignore-scripts && pnpm -r run build

ENV PORT=3000
EXPOSE 3000

CMD ["node", "apps/api-gateway/dist/main.js"]
