name: Release promotion
on:
  pull_request:
    branches: [main]
permissions: { contents: read }
jobs:
  release-promotion:
    runs-on: ubuntu-24.04
    steps:
      - run: test "${{ github.event.pull_request.head.ref }}" = dev
